# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        multimedia.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: scaleway.s3_client
                bucket: '%env(SCALEWAY_BUCKET)%'
                prefix: 'multimedia'
        multimedia.cache:
            adapter: 'aws'
            visibility: public
            options:
                client: scaleway.s3_client
                bucket: '%env(SCALEWAY_BUCKET)%'
                prefix: 'cache/multimedia'
        documents.storage:
            adapter: 'aws'
            visibility: private
            options:
                client: scaleway.s3_client
                bucket: '%env(SCALEWAY_BUCKET)%'
                prefix: 'documents'
