# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    cache: multimedia

    loaders:
        multimedia:
            flysystem:
                filesystem_service: multimedia.storage
    data_loader: multimedia

    filter_sets:
        cache: ~
        multimedia_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { size: [124, 94], position: center, color: '#000000' }
