vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        multimedia:
            upload_destination: multimedia.storage
            uri_prefix: '%env(SCALEWAY_BUCKET_ENDPOINT)%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        document:
            upload_destination: documents.storage
            uri_prefix: '%env(SCALEWAY_BUCKET_ENDPOINT)%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
