vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        multimedia:
            upload_destination: multimedia.storage
            uri_prefix: multimedia
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
