version: "3.7"
services:

  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=fastmdb
      - MYSQL_ROOT_PASSWORD=fastmdb

  php:
    build: ./docker/php
    env_file: docker.env
    volumes:
      - $SSH_AUTH_SOCK:/tmp/agent.sock
      - ~/.composer:/home/.composer
      - ./docker/config/bashrc:/home/.bashrc
      - ./docker/config/bash_aliases:/home/.bash_aliases
      - ./docker/config/inputrc:/home/.inputrc
      - ./docker/data/history:/home/.bash_history
      - ./:/srv/

  nginx:
    image: nginx:1.20.0-alpine
    expose:
      - 80
      - 443
    depends_on:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/certs:/etc/nginx/certs
      - ./:/srv/:ro

  node:
    build:
      context: docker/node
    working_dir: /srv
    volumes:
      - ./:/srv/
    command: echo "node service disabled" && /bin/true

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - node.name=fast-mdb
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601
    depends_on:
      - elastic

  maildev:
    image: djfarrelly/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS

volumes:
  mysql: ~
  elastic: ~
